services:
  - name: satellite-api
    type: web
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/hamzapaul-sudo/satellite-collision-predictor
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
    autoDeploy: true
    healthCheckPath: "/"
    disk:
      name: persistent-storage
      mountPath: /app/storage
